### ISSUE TITLE
Question regarding ip4r and upstream

### ISSUE THREAD

**Issue by mzpqnxow** [RhodiumToad/ip4r#18]
Hey @RhodiumToad I had a question for you about this project, so not really an "issue" per se ...

Have you communicated with or worked with the PostgreSQL devs at all to attempt to have this accepted upstream? While I would really like to use this extension, I am on a relatively unusual CPU architecture (ppc64le, specifically an IBM POWER8) and am a bit hesitant to use any native code extensions without any official "blessing" or at least discussion/review on the PostgreSQL dev mailing list

I see that some of this work derived from the upstream `seg` extension as well as some other prior work that I think was not upstream (`ipr`) which might make such a discussion easier as it leads me to believe you probably followed some generally accepted development practices that the PostgreSQL devs ask of extensions

I realize up-streaming this may not be your intention and you may not have the time to pursue that, if that's the case, no problem. I just thought it couldn't hurt to ask.

I'm going to assume you can understand my hesitation when it comes to introducing "unsupported" native code into a database server, especially on a non-mainstream architecture that many projects do not even attempt to officially support- for example, pandas (which is a very, very widely used project) does not officially support ppc64le, due to its extensive use of native code/Cython and other optimizations

The POWER8 ppc64le chips do not seem to have stumbling blocks that are common with other RISC architectures, which is a plus. For example, the system doesn't throw SIGBUS on unaligned word/half-word loads/stores, so that is one less thing to worry about going wrong when writing C code. Also, being little-endian helps a bit since it effectively eliminates possible byte-order issues manifesting at runtime (I assume your primary target was x86_64 which is also little-endian)

Aside from these two relatively common problem areas that I have some experience in dealing with, I can't think of any obvious areas for trouble that would be specific to the CPU architecture (aside from some subtle performance hits or boosts) but am still applying an abundance of caution

Either way I'll probably test on a development machine- if you're interested in officially supporting this architecture, let me know and I'd be happy to let you know if I run into any issues and provide feedback or PRs

Thanks, really nice work on this

**Comment by RhodiumToad** [comment]
Sorry for late response.

1) I **am** a PostgreSQL dev and committer. (Though I wasn't when I started this project)

2) Upstreaming it was never the intention, not for lack of time but because it shackles the release cycle of the project to that of the upstream, and also there's a major overlap in functionality with the built-in inet/cidr types.

3) Extensibility via third-party modules is a **design goal** of PostgreSQL, and refusing to use modules simply because they're not in the upstream (and note that many popular extensions **cannot** be in the upstream for licensing reasons, the most notable probably being PostGIS and PL/R) is cutting yourself off from a lot of useful tools.

**Comment by mzpqnxow** [comment]
@RhodiumToad I forgot to update this, but after your note, I ended up using `ip4r` and it has worked excellently. Thank you!
