### ISSUE TITLE
Installing on W10 WSL2

### ISSUE THREAD

**Issue by mwpowellhtx** [RhodiumToad/ip4r#19]
Or possibly via W10 "itself", so to speak, i.e. with "native" `make` support.

Problem is, I have `pg` installed on W10. All well and good. But the scripts are looking for `pg_config`. Is it sufficient to add the `pg` binaries folder to the path, for instance? I suspect probably not.

Better might be a pre-built extension for W10... If possible.

Thank you.

**Comment by mwpowellhtx** [comment]
Background, out of the box, I installed `pg` on W10. That's where I'd like to run my `pg` instance. I do have _WSL2_ available, and `Ubuntu`, if necessary...

The starting point for most install examples is:

```SQL
create extension if not exists ip4r;
```

After which I receive,

```
ERROR:  could not open extension control file "C:/Program Files/PostgreSQL/12/share/extension/ip4r.control": No such file or directory
SQL state: 58P01
```

And which, upon further review, `ip4r` is not among the default, installed extensions that are available in `12.5`.

Thoughts?

Thank you...

**Comment by RhodiumToad** [comment]
So the problem from my point of view is this: while PG itself supports a native windows build, as far as I know nobody has made any attempt to provide any support infrastructure to match the PGXS extension system used on Unix-like OSes. Also I don't use windows myself at all, so the only way I can test stuff on it is via a CI service, which can be quite tedious to set up.

**Comment by mwpowellhtx** [comment]
@RhodiumToad Hmm, well if the lift isn't too heavy, I might be game. 

My goal is to potentially support a _TeamSpeak 3_ server `pg`, which I gather they are more geared to true _Linux_ servers, not necessarily deployed on a _Windows_, or _W10_, system.

The TS docs themselves mention setting up for Windows, but also make the assumption, it seems, that `ip4r` is available as an extension. Given the facts about `ip4r`, not sure how they could have tested this, to be honest.

But beyond that, there are potentially interesting geolocation applications that might be interesting as well.

I try to build from _WSL2 Ubuntu_, and I get this far,

```
make: pg_config: Command not found
Makefile:53: *** unsupported PostgreSQL version.  Stop.
```

Hence, above... Have not tried from the perspective of a _Visual Studio_ command prompt, however. When I do, I run into this:

```
M:\Installs\Development\PostgreSQL\extensions\ip4r\ip4r-2.4.1>nmake
Microsoft (R) Program Maintenance Utility Version 14.28.29335.0
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(5) : fatal error U1034: syntax error : separator missing
Stop.
```

**Comment by RhodiumToad** [comment]
The ip4r makefile requires GNU Make because PG itself and the PGXS extension mechanism require that.

So you first need to decide whether you're going to use WSL or native Windows; obviously you can't mix-and-match between the server and ip4r on this.

Building on WSL should be no different to building on Linux directly, but you shouldn't need to build it because ip4r should be available in Ubuntu packages already (it's certainly in the apt.postgresql.org repository). If you do want to build it yourself you need the appropriate postgresql-*-server-dev package installed, and do `make PG_CONFIG=/usr/lib/postgresql/13/bin/pg_config` or whatever version.

Building for native windows would require creating either a project file or a separate makefile for nmake, but I don't know any good way of finding out the correct compilation options to use. Postgresql itself builds natively on windows using a project file that is constructed from the makefiles using a Perl script (see tools/msvc in the postgresql sources).

**Comment by mwpowellhtx** [comment]
Hmm, I see. So it sounds like a viable path forward for me might be to reconsider installing teamspeak in that _WSL2 Ubuntu_ environment.
