### ISSUE TITLE
Make custom constraint

### ISSUE THREAD

**Issue by alex1schenk** [RhodiumToad/ip4r#22]
I'm trying to make a custom constraint where if an iprange is already contained in the table it shouldn't be added. 
Something that looks like this:
```
alter table table_a
add constraint table_a_no_contained_ip_ranges
exclude using gist (pkey_iprange inet_ops WITH &&);
```
The inet ops is what I would use if this was an inet field type and it doesn't work for an iprange field type. When I omit the inet_ops operator type I get strange results. How can I acheive no duplicates contained ranges with this extension?

**Comment by RhodiumToad** [comment]
Sorry for the very late response.

`exclude using gist (pkey_iprange with &&)` should be sufficient. The opclass name is `gist_iprange_ops` if you want to specify it explicitly.

I did not see anything unusual when testing this. I'm closing this due to the delay, if you're still around feel free to reopen it with more detail.
